from app.routers.product import router as product_router
from app.routers.category import router as category_router
from app.routers.customer import router as customer_router
from app.routers.supplier import router as supplier_router
from app.routers.user import router as user_router
from app.routers.sale import router as sale_router
from app.routers.sale_item import router as sale_item_router
from app.routers.payment import router as payment_router
from app.routers.receipt import router as receipt_router