from app.repositories.product import product_repository
from app.repositories.category import category_repository
from app.repositories.customer import customer_repository
from app.repositories.supplier import supplier_repository
from app.repositories.user import user_repository
from app.repositories.sale import sale_repository
from app.repositories.sale_item import sale_item_repository
from app.repositories.payment import payment_repository
from app.repositories.receipt import receipt_repository